apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          env:
          - name: WORDPRESS_DB_HOST
            value: {{ include "wordpress.fullname" . }}-mysql
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "wordpress.fullname" . }}
                key: WORDPRESS_DB_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "wordpress.fullname" . }}
                key: WORDPRESS_DB_PASSWORD
          - name: WP_HOME
            value: {{ .Values.wordpress.env.WP_HOME }}
          - name: WP_SITEURL
            value: {{ .Values.wordpress.env.WP_SITEURL }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}-wordpress  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-phpmyadmin
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "wordpress.phpmyadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordpress.phpmyadmin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.phpmyadmin.image.repository }}:{{ .Values.phpmyadmin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.phpmyadmin.image.pullPolicy }}
          env:
          - name: PMA_ABSOLUTE_URI
            value: {{ .Values.phpmyadmin.env.PMA_ABSOLUTE_URI }}
          - name: PMA_HOST
            value: {{ include "wordpress.fullname" . }}-mysql
          - name: PMA_PORT
            value: "3306"

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
