apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  WORDPRESS_DB_USER: {{ required "Setting username is required!" .Values.mysql.username | b64enc }}
  WORDPRESS_DB_PASSWORD: {{ required "Setting password is required!" .Values.mysql.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ required "Setting password is required!" .Values.mysql.rootPassword | b64enc }}
type: Opaque