apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "wordpress.mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordpress.mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "wordpress.fullname" . }}
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "wordpress.fullname" . }}
                key: WORDPRESS_DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "wordpress.fullname" . }}
                key: WORDPRESS_DB_PASSWORD
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}-mysql

